<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24707" started-at="2018-03-19T06:31:07Z" finished-at="2018-03-19T06:31:32Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24707" started-at="2018-03-19T06:31:07Z" finished-at="2018-03-19T06:31:32Z">
      <class name="yahoo.testcases.LoginSuccessfully">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:yahoo.testcases.LoginSuccessfully@2e11485]" name="beforeSuite" is-config="true" duration-ms="43" started-at="2018-03-19T13:31:07Z" finished-at="2018-03-19T13:31:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:yahoo.testcases.LoginSuccessfully@2e11485]" name="beforeMethod" is-config="true" duration-ms="8398" started-at="2018-03-19T13:31:07Z" finished-at="2018-03-19T13:31:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://goo.gl/4TQGwF]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void yahoo.testcases.LoginSuccessfully.loginSuccessfully()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="loginSuccessfully()[pri:0, instance:yahoo.testcases.LoginSuccessfully@2e11485]" name="loginSuccessfully" duration-ms="15002" started-at="2018-03-19T13:31:16Z" description="Passed test1!" finished-at="2018-03-19T13:31:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccessfully -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:yahoo.testcases.LoginSuccessfully@2e11485]" name="afterMethod" is-config="true" duration-ms="1051" started-at="2018-03-19T13:31:31Z" finished-at="2018-03-19T13:31:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- yahoo.testcases.LoginSuccessfully -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
  <suite name="Suite2" duration-ms="13857" started-at="2018-03-19T06:31:32Z" finished-at="2018-03-19T06:31:46Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13857" started-at="2018-03-19T06:31:32Z" finished-at="2018-03-19T06:31:46Z">
      <class name="yahoo.testcases.LoginSuccessfully3">
        <test-method status="FAIL" signature="beforeMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:yahoo.testcases.LoginSuccessfully3@192d74fb]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-19T13:31:46Z" finished-at="2018-03-19T13:31:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://goo.gl/4TQGwF]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void yahoo.testcases.LoginSuccessfully3.loginSuccessfully()]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.logigear.driver.DriverManager.createWebDriver(DriverManager.java:38)
	at yahoo.testcases.TestBase.beforeMethod(TestBase.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="loginSuccessfully()[pri:0, instance:yahoo.testcases.LoginSuccessfully3@192d74fb]" name="loginSuccessfully" duration-ms="0" started-at="2018-03-19T13:31:46Z" description="Passed test 2" finished-at="2018-03-19T13:31:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.logigear.driver.DriverManager.createWebDriver(DriverManager.java:38)
	at yahoo.testcases.TestBase.beforeMethod(TestBase.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccessfully -->
      </class> <!-- yahoo.testcases.LoginSuccessfully3 -->
      <class name="yahoo.testcases.LoginSuccessfully2">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:yahoo.testcases.LoginSuccessfully2@19fb8826]" name="beforeSuite" is-config="true" duration-ms="0" started-at="2018-03-19T13:31:32Z" finished-at="2018-03-19T13:31:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:yahoo.testcases.LoginSuccessfully2@19fb8826]" name="beforeMethod" is-config="true" duration-ms="5756" started-at="2018-03-19T13:31:32Z" finished-at="2018-03-19T13:31:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://goo.gl/4TQGwF]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void yahoo.testcases.LoginSuccessfully2.loginSuccessfully()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="loginSuccessfully()[pri:0, instance:yahoo.testcases.LoginSuccessfully2@19fb8826]" name="loginSuccessfully" duration-ms="7309" started-at="2018-03-19T13:31:38Z" description="Failed test" finished-at="2018-03-19T13:31:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at yahoo.testcases.LoginSuccessfully2.loginSuccessfully(LoginSuccessfully2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccessfully -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:yahoo.testcases.LoginSuccessfully2@19fb8826]" name="afterMethod" is-config="true" duration-ms="741" started-at="2018-03-19T13:31:45Z" finished-at="2018-03-19T13:31:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- yahoo.testcases.LoginSuccessfully2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite2 -->
</testng-results>
